language: php
warnings_are_errors: false
before_script:
  - |
    echo "TRAVIS_PHP_VERSION:" $TRAVIS_PHP_VERSION;
    php -v;
    php -r 'echo "PHP: ".PHP_VERSION."\n";';
    if [ $(echo "$TRAVIS_PHP_VERSION == 7.0" | bc -l) -eq 1 ]; then
      echo using PHPUnit 5.7.27
      curl -sSfL -o ~/.phpenv/versions/$TRAVIS_PHP_VERSION/bin/phpunit https://phar.phpunit.de/phpunit-5.7.27.phar;
    fi
matrix:
  fast_finish: true
  allow_failures:
  - php: nightly
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: nightly

sudo: false

install:
    composer update

script:
    - find src -name '*.php' | xargs -n 1 -P4 php -l
    - ./vendor/bin/phpunit
