language: php
warnings_are_errors: false

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: nightly

sudo: false

install:
    - composer update

script:
    - find src -name '*.php' | xargs -n 1 -P4 php -l
    - ./vendor/bin/phpunit
