language: php

php:
- 5.6
- 7.0
- 7.1
- 7.2
- 7.3
- 7.4snapshot
- nightly

sudo: false

install:
    composer update

script:
    - find mollie-payments-for-woocommerce -name '*.php' | xargs -n 1 -P4 php -l
    - ./vendor/bin/phpunit
