name: Continuous Integration

on: [push]

jobs:
    run:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-versions: ['5.6', '7.0', '7.1', '7.2', '7.3', '7.4']
            fail-fast: true
        name: PHP ${{ matrix.php-versions }}
        steps:
            -   uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
                    coverage: none

            -   name: install dependencies
                run: composer install --no-interaction --optimize-autoloader
                
            -   name: check syntax
                run: find src -name '*.php' | xargs -n 1 -P4 php -l
                
            -   name: Run PHPUnit
                run: ./vendor/bin/phpunit
