name: PHP integration tests
on:
  push:
    branches:
      - integration-tests
jobs:
    build:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, 'ci skip')"
        continue-on-error: true
        strategy:
            fail-fast: false
            matrix:
                php-versions: ['php72']
        steps:
            -   uses: actions/checkout@v2

#            -   name: Copy wait-for script
#                uses: canastro/copy-file-action@master
#                with:
#                    source: "tests/docker/wait-for.sh"
#                    target: "tests/docker/${{ matrix.php-versions }}/wait-for.sh"

            -   name: Run integration tests
                working-directory: ./tests/docker
                run: |
                  sleep 15
                  docker-compose run php72 composer config --global --auth http-basic.repo.packagist.com token ${{ secrets.PACKAGIST_TOKEN }} && composer install -q -n -a --no-progress --prefer-dist && composer tests:integration"
