name: PHP integration tests
on:
  push:
    branches:
      - integration-tests
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
                  
            -   name: Docker up
                working-directory: ./tests/docker
                run: docker-compose up -d                  

            -   name: Run integration tests
                working-directory: ./tests/docker
                run: |
                  sleep 15
                  docker-compose run php72 composer config --global --auth http-basic.repo.packagist.com token ${{ secrets.PACKAGIST_TOKEN }} && composer install -q -n -a --no-progress --prefer-dist && composer tests:integration
